-- Residential Parking Management System
-- 01_schema_and_seed.sql
-- PowerShell users can run: Get-Content -Encoding UTF8 sql\01_schema_and_seed.sql | mysql -uroot -p --default-character-set=utf8mb4

CREATE DATABASE IF NOT EXISTS parking_system
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

USE parking_system;
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS Card (
  卡号 VARCHAR(30) NOT NULL,
  车牌号 VARCHAR(30) NOT NULL,
  车主姓名 VARCHAR(50) NOT NULL,
  联系电话 VARCHAR(30) NOT NULL,
  车卡状态 VARCHAR(20) NOT NULL DEFAULT '正常',
  创建时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  更新时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (卡号),
  UNIQUE KEY uk_card_plate (车牌号),
  CONSTRAINT chk_card_phone CHECK (联系电话 REGEXP '^[0-9+ -]{6,30}$'),
  CONSTRAINT chk_card_status CHECK (车卡状态 IN ('正常', '挂失', '注销'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ParkingSpace (
  车位编号 VARCHAR(30) NOT NULL,
  车位状态 VARCHAR(20) NOT NULL DEFAULT '空闲',
  当前停放车牌 VARCHAR(30) NULL,
  固定车位卡号 VARCHAR(30) NULL,
  创建时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  更新时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (车位编号),
  CONSTRAINT chk_space_status CHECK (车位状态 IN ('空闲', '有车')),
  CONSTRAINT fk_space_fixed_card FOREIGN KEY (固定车位卡号) REFERENCES Card(卡号)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ParkingRecord (
  记录编号 VARCHAR(80) NOT NULL,
  卡号 VARCHAR(30) NOT NULL,
  停放车位编号 VARCHAR(30) NOT NULL,
  入库时间 DATETIME NOT NULL,
  出库时间 DATETIME NULL,
  收费数额 DECIMAL(10,2) NULL,
  PRIMARY KEY (记录编号),
  CONSTRAINT fk_record_card FOREIGN KEY (卡号) REFERENCES Card(卡号)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_record_space FOREIGN KEY (停放车位编号) REFERENCES ParkingSpace(车位编号)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_record_time CHECK (出库时间 IS NULL OR 出库时间 >= 入库时间),
  CONSTRAINT chk_record_fee CHECK (收费数额 IS NULL OR 收费数额 >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AuditLog (
  审计编号 BIGINT NOT NULL AUTO_INCREMENT,
  表名 VARCHAR(50) NOT NULL,
  操作类型 VARCHAR(20) NOT NULL,
  操作时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  操作员 VARCHAR(50) NULL DEFAULT '系统',
  记录内容 TEXT NOT NULL,
  PRIMARY KEY (审计编号),
  CONSTRAINT chk_audit_operation CHECK (操作类型 IN ('INSERT', 'UPDATE', 'DELETE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS BackupHistory (
  备份编号 BIGINT NOT NULL AUTO_INCREMENT,
  备份时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  备份文件 VARCHAR(255) NOT NULL,
  备份说明 VARCHAR(255) NULL,
  PRIMARY KEY (备份编号)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TRIGGER IF EXISTS trg_card_encrypt_bi;
DROP TRIGGER IF EXISTS trg_card_encrypt_bu;
DROP VIEW IF EXISTS v_card_masked;
DROP TABLE IF EXISTS ParkingRecordArchive;

SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Card' AND COLUMN_NAME = '车牌号密文') > 0, 'ALTER TABLE Card DROP COLUMN 车牌号密文', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Card' AND COLUMN_NAME = '车卡状态') = 0, 'ALTER TABLE Card ADD COLUMN 车卡状态 VARCHAR(20) NOT NULL DEFAULT ''正常'' AFTER 联系电话', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
UPDATE Card SET 车卡状态 = '正常' WHERE 车卡状态 IS NULL OR 车卡状态 = '';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Card' AND COLUMN_NAME = '创建时间') = 0, 'ALTER TABLE Card ADD COLUMN 创建时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Card' AND COLUMN_NAME = '更新时间') = 0, 'ALTER TABLE Card ADD COLUMN 更新时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ParkingSpace' AND COLUMN_NAME = '创建时间') = 0, 'ALTER TABLE ParkingSpace ADD COLUMN 创建时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ParkingSpace' AND COLUMN_NAME = '更新时间') = 0, 'ALTER TABLE ParkingSpace ADD COLUMN 更新时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

INSERT IGNORE INTO Card (卡号, 车牌号, 车主姓名, 联系电话) VALUES
('C1000001', '粤A10001', '张三', '13800000001'),
('C1000002', '粤A10002', '李四', '13800000002'),
('C1000003', '粤A10003', '王五', '13800000003');

UPDATE ParkingRecord pr
JOIN ParkingSpace old_space ON old_space.车位编号 = pr.停放车位编号
JOIN ParkingSpace new_space ON new_space.车位编号 = CONCAT(LEFT(old_space.车位编号, 2), RIGHT(old_space.车位编号, 2))
SET pr.停放车位编号 = new_space.车位编号
WHERE old_space.车位编号 REGEXP '^[AB]-0[0-9][0-9]$'
  AND new_space.车位状态 = '空闲';

UPDATE ParkingSpace new_space
JOIN ParkingSpace old_space ON new_space.车位编号 = CONCAT(LEFT(old_space.车位编号, 2), RIGHT(old_space.车位编号, 2))
SET new_space.车位状态 = old_space.车位状态,
    new_space.当前停放车牌 = old_space.当前停放车牌
WHERE old_space.车位编号 REGEXP '^[AB]-0[0-9][0-9]$'
  AND old_space.车位状态 = '有车'
  AND new_space.车位状态 = '空闲';

UPDATE ParkingRecord SET 停放车位编号 = 'B-99' WHERE 停放车位编号 = 'B-DEMO';

DELETE ps FROM ParkingSpace ps
LEFT JOIN ParkingRecord pr ON pr.停放车位编号 = ps.车位编号
WHERE pr.记录编号 IS NULL
  AND (ps.车位编号 REGEXP '^[AB]-[0-9]{3}$' OR ps.车位编号 = 'B-DEMO');

INSERT IGNORE INTO ParkingSpace (车位编号, 车位状态, 当前停放车牌, 固定车位卡号)
SELECT
  CONCAT('A-', LPAD(t.n * 10 + o.n, 2, '0')),
  '空闲',
  NULL,
  CASE t.n * 10 + o.n
    WHEN 0 THEN 'C1000001'
    WHEN 1 THEN 'C1000002'
    WHEN 2 THEN 'C1000003'
    ELSE NULL
  END
FROM
  (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t
  CROSS JOIN
  (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) o;

INSERT IGNORE INTO ParkingSpace (车位编号, 车位状态, 当前停放车牌, 固定车位卡号)
SELECT
  CONCAT('B-', LPAD(t.n * 10 + o.n, 2, '0')),
  '空闲',
  NULL,
  NULL
FROM
  (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t
  CROSS JOIN
  (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) o;
